engine:
  type: "in_memory"
network:
  address: "127.0.0.1:8081"
  max_connections: 100
  max_message_size: "8B"
  idle_timeout: 5m
logging:
  level: "info"
  output: "stdout"
wal:
  enabled: false
  flushing_batch_size: 100
  flushing_batch_timeout: 10ms
  segment_size: "10MB"
  data_directory: "./data/wal"
